spring:
  kafka:
    # broker实例初始化地址，以ip:port数据对形式存在，并以逗号分隔
    # kafka会从这个初始化地址出发，自动发现完整的集群成员信息
    bootstrap-servers: 139.129.108.126:9092, 139.129.108.126:9093, 139.129.108.126:9094
    producer:
      # 向broker端发送的任何消息的式都必须是字节数组
      # 键序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 值序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 消息会被发送到指定topic分区leader所在的broker上， producer会等待从该leader broker返回消息的写入结果
      # acks含义: 给producer发送响应前，leader broker必须确保已成功写入该消息的副本数
      # 0：无须任何副本成功写入  1:leader副本须成功写入  all/-1：所有副本须成功写入
      acks: -1
      # 缓存消息的缓冲区大小，单位字节 默认32MB
      # kafka异步架构：消息会先发往内存缓冲区，由另外的读线程从内存缓冲区中读取然后做真正的发送
      buffer-memory: 33554432
      # 消息是否压缩，默认none，即不压缩  其他选项：gzip、snappy、lz4、zstd
      compression-type: none
      # 当多个消息发送到同一个分区时，会将多条消息封装进一个batch中来减少与broker的交互，默认16Kb
      batch-size: 16384
      # 用于跟踪请求源，向broker发出请求时，会带上这个字符串
      client-id: "yiou_data_client_1"
      # 以下是追加的其他配置项，需要使用properties
      properties:
        linger.ms: 4


